from src.agent_constructor.agent import Agent
from openai import OpenAI
from typing import List
from src.agent_constructor.chunkers import Chunk
from src.agent_constructor.core import Text
from src.pipelines.registry import register_component
from src.pipelines.constants import ComponentNames

@register_component(ComponentNames.CORAG_SUB_GENERATOR)
class CoRAGSubQueryGeneratorAgent(Agent):
    def __init__(self, url: str = None, model_name: str = None):
        super().__init__("corag_subquery_generator")
        self.dummy_mode = not (url and model_name)
        
        if not self.dummy_mode:
            self.client = OpenAI(
                base_url=url,
                api_key="vllm"
            )

        self.model_name = model_name
        self.system_prompt = """You are using a search engine to answer the main query by iteratively searching the web. Given the following
intermediate queries and answers, generate a new simple follow-up question that can help answer the main
query. You may rephrase or decompose the main query when previous answers are not helpful. Ask simple
follow-up questions only as the search engine may not understand complex questions."""

    def run(self, task: Text, prev_qna: List = []) -> Text:

        if self.dummy_mode:
            return [f"#{i} Subquery of query '{task}'" for i in range(self.max_num_queries)]

        prev_qna_prompt = ""
        for i, (q,a) in enumerate(prev_qna):
            prev_qna_prompt += f"Sub-query {i+1}: {q}\nSub-answer {i+1}: {a}\n"



        user_prompt = f"""## Previous intermediate queries and answers
{prev_qna_prompt if prev_qna_prompt else "None"}
## Task description
{task}

Respond with a simple follow-up question that will help answer the main query, do not explain yourself or
output anything else. Remeber, that follow-up question should not be adressed to user but to search-engine.
"""

        response = self.client.chat.completions.create(
            model=self.model_name,
            messages=[
                {"role": "system", "content": self.system_prompt},
                {"role": "user", "content": user_prompt}],
            temperature=0,
        )

        return response.choices[0].message.content
    

@register_component(ComponentNames.CORAG_SUB_SOLVER)
class CoRAGSubSolver(Agent):
    def __init__(self, url: str = None, model_name: str = None, max_num_queries: int = 5):
        super().__init__("corag_sub_solver")
        self.dummy_mode = not (url and model_name)
        
        if not self.dummy_mode:
            self.client = OpenAI(
                base_url=url,
                api_key="vllm"
            )

        self.model_name = model_name
        self.max_num_queries = max_num_queries
        self.system_prompt = """Given the following documents, generate an appropriate answer for the query. DO NOT hallucinate any
information, only use the provided documents to generate the answer. Respond “No relevant information
found” if the documents do not contain useful information."""

    def run(self, task: Text, context: List[Chunk]) -> Text:

        if self.dummy_mode:
            return [f"#{i} Subquery of query '{task}'" for i in range(self.max_num_queries)]

        context_prompt = ""
        for chunk in context:
            context_prompt += f"{chunk.text}\n"

        user_prompt = f"""## Documents
{context_prompt if context_prompt else "None"}

## Query
{task}

Respond with a concise answer only, do not explain yourself or output anything else.
"""

        response = self.client.chat.completions.create(
            model=self.model_name,
            messages=[
                {"role": "system", "content": self.system_prompt},
                {"role": "user", "content": user_prompt}],
            temperature=0,
        )

        return response.choices[0].message.content

@register_component(ComponentNames.CORAG_FINAL_SOLVER)
class CoRAGFinalSolver(Agent):
    def __init__(self, url: str = None, model_name: str = None, max_num_queries: int = 5):
        super().__init__("corag_final_solver")
        self.dummy_mode = not (url and model_name)
        
        if not self.dummy_mode:
            self.client = OpenAI(
                base_url=url,
                api_key="vllm"
            )

        self.model_name = model_name
        self.max_num_queries = max_num_queries
        self.system_prompt = """Given the following intermediate queries and answers, generate a final answer for the main query by
combining relevant information. Note that intermediate answers are generated by an LLM and may not
always be accurate."""

    def run(self, task: Text, context: Text) -> Text:

        if self.dummy_mode:
            return [f"#{i} Subquery of query '{task}'" for i in range(self.max_num_queries)]

        user_prompt = f"""{context}
## Task description
{task}

Respond with an appropriate answer only, do not explain yourself or output anything else.
"""

        response = self.client.chat.completions.create(
            model=self.model_name,
            messages=[
                {"role": "system", "content": self.system_prompt},
                {"role": "user", "content": user_prompt}],
            temperature=0,
        )

        return response.choices[0].message.content
