"""ApiReferenceGenreFilter — keep API-reference docs by CONTENT, no metadata.

Universal counterpart of ``ApiReferenceSectionFilter``. Reproduces the same
keep/drop split as the manual ``apis.db`` (keep API reference, drop narrative
user_guide / tutorial / examples / dev_notes), but decides purely from the
document text — it never looks at ``metadata['section']`` or ``library``. This
is the grant deliverable: a *universal* genre filter that transfers to any
code-documentation corpus without a clean section taxonomy.

Genre signals (measured on docs_database_examples.db, exp6 analysis):
  KEEP (API-reference genre)
    - structured field headers: Parameters / Returns / Return type / Raises /
      Attributes / Yields / Warns / Variables / Other Parameters
      (reference 49.9% vs narrative 0.5%)
    - ``[source]`` tag  (46.8% vs 0.3%)
    - API signature line ``name.path( args ) [source] #``  (51.7% vs 8.6%)
  DROP (narrative genre)
    - Sphinx / tutorial boilerplate ("Go to the end", "Total running time",
      "Gallery generated by Sphinx-Gallery", "Download Jupyter", "Created On:",
      "download the full example code")  (reference 1.0% vs tutorial/examples/
      dev_notes 95-100%)
    - long LaTeX-heavy prose (user_guide conceptual pages)

Decision rule (validated F1 ~= 97% vs the section oracle: 94% reference recall,
~95% narrative dropped, 99.7% precision):
    if boilerplate:                       drop
    if field_header or [source]:          keep
    if signature and len < max_sig_len:   keep
    else:                                 keep iff (len < max_stub_len and no LaTeX)

The last branch handles the ~50% of reference docs that carry no strong signal:
short structured stubs (attributes, constants, module pages) are kept; long
LaTeX-heavy prose (user guides) is dropped.

Document-level filter: used by ``SimplePipelineWithDocFilter`` (pipeline type
``SIMPLE_WITH_DOC_FILTER``), runs BEFORE chunking. No LLM, deterministic, fast.
"""

import re
from typing import List

from src.agent_constructor.core import Document
from src.agent_constructor.filters import DocumentFilter


# API signature line, e.g. "torch.nn.utils.weight_norm. remove_weight_norm
# ( module , name = 'weight' ) [source] #"  or  "class scipy.stats. levy ( ) #"
_SIG_RE = re.compile(r"\w[\w.]*\s*\([^\n]*\)\s*(\[source\])?\s*#")

# Structured field headers on their own line (the cleanest reference marker).
_FIELD_RE = re.compile(
    r"(?m)^\s*(Parameters|Returns|Return type|Raises|Attributes|Yields|Warns|"
    r"Variables|Other Parameters)\s*$"
)

# Sphinx-gallery / tutorial / dev-notes boilerplate (strong narrative marker).
_BOILER_RE = re.compile(
    r"Go to the end|Total running time of the script|"
    r"Gallery generated by Sphinx-Gallery|Download\s+Jupyter|Created On:|"
    r"download the full example code"
)

_LATEX_MARKERS = ("\\(", "\\[", "\\frac", "\\alpha", "\\beta")


def _has_latex(text: str) -> bool:
    return any(m in text for m in _LATEX_MARKERS)


class ApiReferenceGenreFilter(DocumentFilter):
    """Keep API-reference-genre documents, drop narrative ones, by content only.

    Args:
        name: block name.
        max_sig_len: docs with an API signature but no field header are kept
            only if shorter than this (a long doc that merely mentions a call
            is narrative, not a reference entry). Default 3000.
        max_stub_len: signal-less docs are kept only if shorter than this and
            free of LaTeX (short structured stubs vs long prose). Default 800.
    """

    def __init__(
        self,
        name: str = "api_genre_filter",
        max_sig_len: int = 3000,
        max_stub_len: int = 800,
    ):
        super().__init__(name)
        self.max_sig_len = max_sig_len
        self.max_stub_len = max_stub_len

    def _is_reference(self, text: str) -> bool:
        if _BOILER_RE.search(text):
            return False
        if _FIELD_RE.search(text) or "[source]" in text:
            return True
        if _SIG_RE.search(text) and len(text) < self.max_sig_len:
            return True
        return len(text) < self.max_stub_len and not _has_latex(text)

    def apply(self, documents: List[Document]) -> List[Document]:
        return [doc for doc in documents if self._is_reference(doc.text or "")]
