components:
  # ===== DBs =====
  LOCAL_DB:
    import: src.agent_constructor.db.LocalDB

  LOCAL_RAPTOR_DB:
    import: src.agent_constructor.db.LocalRaptorDB

  # ===== Chunkers =====
  DUMMY_CHUNKER:
    import: src.agent_constructor.chunkers.DummyChunker

  SIMPLE_CHUNKER:
    import: src.agent_constructor.chunkers.SimpleChunker

  # ===== Filters =====
  LENGTH_FILTER:
    import: src.agent_constructor.filters.LengthFilter

  # ===== Context Assemblers =====
  CORAG_CONTEXT_ASSEMBLER:
    import: src.agent_constructor.context_engine.CoRAGContextAssembler

  # ===== Agents: General =====
  DUMMY_AGENT:
    import: src.agents.general.DummyAgent

  SIMPLE_AGENT:
    import: src.agents.general.SimpleAgent

  EMBEDDING_AGENT:
    import: src.agents.general.EmbeddingAgent

  TFIDF_EMBEDDING:
    import: src.agents.general.TFIDFEmbedding

  # ===== Agents: Generation =====
  EVAL_GENERATOR:
    import: src.agents.generation.CodeEvalGenerator

  INCORRECT_GENERATOR:
    import: src.agents.generation.IncorrectExampleGenerator

  INSTRUCT_GENERATOR:
    import: src.agents.generation.InstuctGenerator
  
  RANDOM_WORD_GENERATOR:
    import: src.agents.generation.RandomWordGenerator
  
  SHOTS_GENERATOR:
    import: src.agents.generation.ZeroFewShotGenerator

  # ===== Agents: Pipelines (MAPS / REWOO) =====
  MAPS_ALIGNER:
    import: src.agents.pipelines.AlignerMAPS

  MAPS_CRITIC:
    import: src.agents.pipelines.CriticMAPS

  MAPS_MANAGER:
    import: src.agents.pipelines.ManagerMAPS

  MAPS_SCHOLAR:
    import: src.agents.pipelines.ScholarMAPS

  MAPS_SOLVER:
    import: src.agents.pipelines.SolverMAPS

  MAPS_USER_PROXY:
    import: src.agents.pipelines.UserProxyMAPS

  REWOO_PLANNER:
    import: src.agents.pipelines.PlannerREWOO

  REWOO_SOLVER:
    import: src.agents.pipelines.SolverREWOO

  REWOO_WORKER:
    import: src.agents.pipelines.WorkerREWOO

  # ===== Agents: Planning =====
  CORAG_SUB_GENERATOR:
    import: src.agents.rag.CoRAGSubQueryGeneratorAgent

  CORAG_SUB_SOLVER:
    import: src.agents.rag.CoRAGSubSolver

  CORAG_FINAL_SOLVER:
    import: src.agents.rag.CoRAGFinalSolver

  RAPTOR_QA_AGENT:
    import: src.agents.rag.RaptorQAAgent

  RAPTOR_SUMM_AGENT:
    import: src.agents.rag.RaptorSummarizationAgent

  # ===== Retrievers =====
  CORAG_RETRIEVER:
    import: src.rag.CoRAGRetriever

  RAPTOR_RETRIEVER:
    import: src.rag.RaptorRetriever

  INSTRUCT_RETRIEVER:
    import: src.rag.InstructRAGRetriever
