import inspect
from typing import Dict, Any, Literal

from src.tools.base_tool import BaseTool
from src.agents.critique.critic.main import Critic
from src.agents.critique.decrim.main import Decrim
from src.agents.critique.reflexion.main import Reflexion
from src.agents.critique.self_refine.main import SelfRefine


# Tool descriptions advertised to the calling agent (via get_prompt_description).
_CODE_DESCRIPTION = (
    "A tool for invoking the critic agent to evaluate the correctness and quality "
    "of code generated by a ReAct agent for a given task."
)
_MC_DESCRIPTION = (
    "A tool for invoking the critic agent on a MULTIPLE-CHOICE code question: given "
    "the problem with options A/B/C/D and the chosen option, it reports — with concrete, "
    "verifiable reasons — whether that option is reference-correct."
)
_CODE_ANSWER_DESC = (
    "The full response from the agent. MUST include the generated code snippet, as the "
    "critic needs to analyze the code implementation to provide accurate feedback."
)
_MC_ANSWER_DESC = (
    "The agent's current answer: the chosen option letter (A, B, C, or D) together with "
    "the reasoning behind it, so the critic can check whether that option is correct."
)


class CriticTool(BaseTool):

    _AGENT_REGISTRY: Dict[str, type] = {
        "critic": Critic,
        "decrim": Decrim,
        "reflexion": Reflexion,
        "self_refine": SelfRefine,
    }

    def __init__(
        self,
        name: Literal["critic", "decrim", "reflexion", "self_refine"] = "critic",
        description: str = None,
        url: str = None,
        model_name: str = None,
        dataset: str = "ds1000",
    ):
        self.dataset = dataset
        is_mc = dataset == "codemmlu"
        if description is None:
            description = _MC_DESCRIPTION if is_mc else _CODE_DESCRIPTION
        self._answer_description = _MC_ANSWER_DESC if is_mc else _CODE_ANSWER_DESC

        super().__init__(name=name, description=description)

        if name not in self._AGENT_REGISTRY:
            raise ValueError(
                f"Unknown method of criticism: '{name}'. "
                f"Available options: {', '.join(self._AGENT_REGISTRY.keys())}"
            )
        agent_class = self._AGENT_REGISTRY[name]
        agent_kwargs = dict(name=name, model_name=model_name, openai_api_base_url=url)
        # Only critics that accept a `dataset` arg get it (currently Critic, Decrim,
        # Reflexion, SelfRefine); others keep their original signature until adapted.
        if "dataset" in inspect.signature(agent_class.__init__).parameters:
            agent_kwargs["dataset"] = dataset
        self.critic_agent = agent_class(**agent_kwargs)

    def get_schema(self) -> Dict[str, Any]:
        """Возвращает описание инструмента в формате OpenAI Tools API."""
        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": {
                    "type": "object",
                    "properties": {
                        "task": {
                            "type": "string",
                            "description": "The original task or question that needs to be solved.",
                        },
                        "answer": {
                            "type": "string",
                            "description": self._answer_description,
                        }
                    },
                    "required": ["task", "answer"],
                },
            },
        }

    def __call__(self, task: str, answer: str) -> str:
        return self.critic_agent.run(task, answer)
