from typing import Dict, Any, Literal

from src.tools.base_tool import BaseTool
from src.agents.critique.critic.main import Critic
from src.agents.critique.decrim.main import Decrim
from src.agents.critique.reflexion.main import Reflexion
from src.agents.critique.self_refine.main import SelfRefine


class CriticTool(BaseTool):
    
    _AGENT_REGISTRY: Dict[str, type] = {
        "critic": Critic,
        "decrim": Decrim,
        "reflexion": Reflexion,
        "self_refine": SelfRefine,
    }

    def __init__(
        self,
        name: Literal["critic", "decrim", "reflexion", "self_refine"] = "critic",
        description: str = "A tool for invoking the critic agent to evaluate the correctness and quality of code generated by a ReAct agent for a given task.",
        url: str = None,
        model_name: str = None
    ):
        super().__init__(name=name, description=description)
        
        if name not in self._AGENT_REGISTRY:
            raise ValueError(
                f"Unknown method of criticism: '{name}'. "
                f"Available options: {', '.join(self._AGENT_REGISTRY.keys())}"
            )
        agent_class = self._AGENT_REGISTRY[name]
        self.critic_agent = agent_class(name=name, model_name=model_name, openai_api_base_url=url)

    def get_schema(self) -> Dict[str, Any]:
        """Возвращает описание инструмента в формате OpenAI Tools API."""
        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": {
                    "type": "object",
                    "properties": {
                        "task": {
                            "type": "string",
                            "description": "The original task or question that needs to be solved.",
                        },
                        "answer": {
                            "type": "string",
                            "description": "The full response from the agent. MUST include the generated code snippet, as the critic needs to analyze the code implementation to provide accurate feedback.",
                        }
                    },
                    "required": ["task", "answer"],
                },
            },
        }

    def __call__(self, task: str, answer: str) -> str:
        return self.critic_agent.run(task, answer)
